version: '{build}'

cache:
  - '%USERPROFILE%\.nuget\packages -> appveyor.yml, **\project.json'
  - js-test\node_modules -> js-test\package.json
  - js-test\bower_components -> js-test\bower.json
  - net\packages -> **\packages.config

install:
  - ps: iex ((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/dotnet/cli/v1.0.0-rc2/scripts/obtain/install.ps1'))
  - cd js-test && npm install
  - cd js-test && node_modules\.bin\bower install

before_build:
  - dotnet restore --quiet
  - nuget restore net\DevExtreme.AspNet.Data.Tests.NET40
  - powershell -File build\replace-meta.ps1 %APPVEYOR_BUILD_NUMBER% %APPVEYOR_REPO_TAG_NAME%

build_script:
  - dotnet build net\DevExtreme.AspNet.Data
  - dotnet build net\DevExtreme.AspNet.Data.Tests
  - dotnet build net\Sample
  - msbuild net\DevExtreme.AspNet.Data.Tests.NET40\DevExtreme.AspNet.Data.Tests.NET40.sln /v:q

test_script:
  - js-test\node_modules\.bin\jshint js
  - cd js-test && node_modules\.bin\karma start karma.js
  - dotnet test net\DevExtreme.AspNet.Data.Tests -f netcoreapp1
  - xunit.console.clr4 net\DevExtreme.AspNet.Data.Tests.NET40\bin\Debug\DevExtreme.AspNet.Data.Tests.dll /appveyor

after_test:
  - dotnet pack net\DevExtreme.AspNet.Data --configuration=Release

artifacts:
  - path: net\DevExtreme.AspNet.Data\bin\Release\*.nupkg