version: '{build}'

environment:
  DNX_VERSION: '1.0.0-rc1-update1'

cache:
  - '%USERPROFILE%\.dnx\runtimes -> appveyor.yml'
  - '%USERPROFILE%\.dnx\packages -> appveyor.yml, **\project.json'
  - js-test\node_modules -> js-test\package.json
  - js-test\bower_components -> js-test\bower.json
  - net\packages -> **\packages.config

install:
  - ps: iex ((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1'))
  - dnvm install %DNX_VERSION% -r coreclr
  - cd js-test && npm install
  - cd js-test && node_modules\.bin\bower install

before_build:
  - dnu restore --quiet
  - nuget restore net\DevExtreme.AspNet.Data.Tests.NET40
  - powershell -File build\replace-meta.ps1 %APPVEYOR_BUILD_NUMBER% %APPVEYOR_REPO_TAG_NAME%

build_script:
  - dnu build net\DevExtreme.AspNet.Data --quiet
  - dnu build net\DevExtreme.AspNet.Data.Tests --quiet  
  - dnu build net\Sample --quiet  
  - msbuild net\DevExtreme.AspNet.Data.Tests.NET40\DevExtreme.AspNet.Data.Tests.NET40.sln /v:q

test_script:
  - js-test\node_modules\.bin\jshint js
  - js-test\node_modules\.bin\node-qunit-phantomjs js-test\test.html
  - dnx -p net\DevExtreme.AspNet.Data.Tests test
  - xunit.console.clr4 net\DevExtreme.AspNet.Data.Tests.NET40\bin\Debug\DevExtreme.AspNet.Data.Tests.dll /appveyor

after_test:
  - dnu pack net\DevExtreme.AspNet.Data --configuration=Release --quiet

artifacts:
  - path: net\DevExtreme.AspNet.Data\bin\Release\*.nupkg